version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:4.8.2-jessie
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run:
          name: List
          command: 'ls -l'
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: # run tests
          name: newman
          command: npm install -g newman
  tests:
    machine:
        enabled: true    
    steps: # a collection of executable commands     
      - run:
          name: postman
          command: sh ./execute
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build