version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10-browsers-legacy # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run: # install newman
          name: install newman
          command: 'sudo npm install -g newman'   
      - run:
          name: mkdir test results
          command: 'mkdir /tmp/test-results'                 
      - run:
          name: list
          command: 'sudo ls -l'
      - run:
          name: pwd
          command: 'sudo pwd'          
      - run:
          name: postman
          command: 'sudo sh ./execute.sh'           
      - store_test_results:
          path: ~/newman    
      - run:
          name: list test results
          command: 'sudo ls -l ~/newman'   
      - run:
          name: list root directory
          command: 'sudo ls -l '                                         
workflows:
  version: 2
  build-and-test:
    jobs:
      - build